---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: "Get Github organization members"
      set_fact:
        users: "{{ lookup('github_team_members', wantlist=True)|map('lower')|list }}"

    - name: "Debug - display Github organization members"
      debug:
        msg: "{{ item }}"
      with_items: "{{ users }}"

    - name: "Create users"
      user:
        name: "{{ item }}"
      with_items: "{{ users }}"

    - name: "Get Github organization members SSH public keys"
      set_fact:
        pubkeys: "{{ pubkeys|default({}) |
                      combine( {item: lookup('github_ssh_pubkeys',
                                              login=item,
                                              wantlist=True) } ) }}"
      with_items: "{{ users }}"

    - name: "Ensure .ssh directory exist"
      file:
        path: "/home/{{ item }}/.ssh"
        state:  directory
        owner:  "{{ item }}"
        group:  "{{ item }}"
        mode: "0755"
      with_items: "{{ users }}"

    - name: "Define authorized keys"
      template:
        src: authorized_keys.j2
        dest: "/home/{{ item.key }}/.ssh/authorized_keys"
        owner:  "{{ item.key }}"
        group:  "{{ item.key }}"
        mode: "0644"
      with_dict: "{{ pubkeys }}"
