---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: "Get Github organization members"
      set_fact:
        users: "{{ lookup('github_team_members', wantlist=True) }}"

    - name: "Debug - display Github organization members"
      debug:
        msg: "{{ item }}"
      with_items: "{{ users }}"

    - name: "Get Github organization members SSH public keys"
      set_fact:
        pubkeys: "{{ pubkeys|default({}) |
                      combine( {item: lookup('github_ssh_pubkeys',
                                              login=item,
                                              wantlist=True) } ) }}"
      with_items: "{{ users }}"

    - name: "Debug - display SSH public keys"
      debug:
        msg: "{{ item.key }}"
      with_dict: "{{ pubkeys }}"
